(function (root) {
  "use strict";

  var AI_PHRASES = [
    /\bleverage(d|s|ing)?\b/i,
    /\butilize(d|s|ing)?\b/i,
    /\bdelve(d|s|ing)?\b/i,
    /\brobust\b/i,
    /\bcutting[- ]edge\b/i,
    /\bseamless(ly)?\b/i,
    /\bsynerg(y|ies|istic)\b/i,
    /\bpassionate about\b/i,
    /\bresults-driven\b/i,
    /\bdetail-oriented\b/i,
    /\bproven track record\b/i,
    /\bin today's (fast-paced|ever-changing)\b/i,
    /\bplay a (pivotal|crucial) role\b/i,
    /\bharness the power\b/i,
    /\bmove the needle\b/i
  ];

  var WATERMARK_MARKERS = [
    "watermark",
    "chatgpt",
    "openai",
    "generated by",
    "generated with",
    "ai generated"
  ];

  function collectText(resume) {
    var parts = [
      resume.name,
      resume.headline,
      resume.location,
      resume.relocation,
      resume.phone,
      resume.email,
      resume.linkedin
    ];
    Object.keys(resume.skills || {}).forEach(function (key) {
      parts.push(key, resume.skills[key]);
    });
    (resume.experience || []).forEach(function (job) {
      parts.push(job.company, job.role, job.subtitle, job.location, job.dates);
    });
    (resume.bullets || []).forEach(function (b) {
      parts.push(b.compiled, b.situation, b.task, b.action, b.result);
    });
    (resume.projects || []).forEach(function (p) {
      parts.push(p.name, p.context, p.tools, p.line);
    });
    (resume.education || []).forEach(function (ed) {
      parts.push(ed.school, ed.degree, ed.location, ed.dates, ed.detail);
    });
    return parts.filter(Boolean).join("\n");
  }

  function findUnicodeIssues(text) {
    var issues = [];
    if (/[\u2013\u2014\u2015]/.test(text)) {
      issues.push("En dash or em dash found. ATS and some AI scanners flag these. Use a hyphen or the word 'to'.");
    }
    if (/[\u2018\u2019\u201C\u201D]/.test(text)) {
      issues.push("Curly quotes found. Use straight ' and \" only.");
    }
    if (/[\u00A0\u202F\u2007\u2009]/.test(text)) {
      issues.push("Non-breaking or thin spaces found. These can look like a generator watermark.");
    }
    if (/[\u200B\u200C\u200D\uFEFF\u2060]/.test(text)) {
      issues.push("Zero-width characters found. Remove them. They are a common hidden watermark.");
    }
    if (/[\u00AD]/.test(text)) {
      issues.push("Soft hyphen found. Strip it before export.");
    }
    if (/[^\S\r\n]{2,}/.test(text)) {
      /* extra spaces are fine; skip */
    }
    return issues;
  }

  function findAiPhrases(text) {
    var hits = [];
    AI_PHRASES.forEach(function (re) {
      var m = text.match(re);
      if (m) hits.push(m[0]);
    });
    return hits;
  }

  function keywordHits(text, keywords) {
    var lower = text.toLowerCase();
    return (keywords || []).map(function (kw) {
      var found = lower.indexOf(kw.toLowerCase()) !== -1;
      return { keyword: kw, found: found };
    });
  }

  function scoreAts(resume, template) {
    var text = collectText(resume);
    var unicode = findUnicodeIssues(text);
    var phrases = findAiPhrases(text);
    var keywords = keywordHits(text, template.atsKeywords || []);
    var foundCount = keywords.filter(function (k) { return k.found; }).length;
    var keywordScore = keywords.length ? Math.round((foundCount / keywords.length) * 100) : 100;

    var checks = [];
    var bullets = resume.bullets || [];
    if (bullets.length > 3) {
      checks.push({ ok: false, label: "Max 3 bullets", detail: bullets.length + " bullets present. Cut to 3." });
    } else if (bullets.length === 0) {
      checks.push({ ok: false, label: "Max 3 bullets", detail: "No STAR bullets yet." });
    } else {
      checks.push({ ok: true, label: "Max 3 bullets", detail: bullets.length + " of 3." });
    }

    bullets.forEach(function (b, i) {
      var missing = ["situation", "task", "action", "result"].filter(function (k) {
        return !String(b[k] || "").trim();
      });
      checks.push({
        ok: missing.length === 0 && String(b.compiled || "").trim().length > 0,
        label: "STAR bullet " + (i + 1),
        detail: missing.length ? "Missing " + missing.join(", ") : "Situation, task, action, and result are filled."
      });
    });

    var hasName = !!(resume.name && resume.email && resume.phone);
    checks.push({
      ok: hasName,
      label: "Contact line",
      detail: hasName ? "Name, email, and phone are present." : "ATS needs name, email, and phone in plain text."
    });

    var hasSummary = !!String(resume.summary || "").trim();
    checks.push({
      ok: !hasSummary,
      label: "No summary",
      detail: hasSummary ? "Remove the summary. Recruiters and ATS get Skills, Experience, Projects, and Education only." : "No summary block."
    });

    var namedProjects = (resume.projects || []).filter(function (p) {
      return String(p.name || "").trim() && String(p.line || "").trim();
    });
    checks.push({
      ok: namedProjects.length > 0,
      label: "Projects",
      detail: namedProjects.length
        ? namedProjects.length + " project" + (namedProjects.length === 1 ? "" : "s") + " with a one-line result."
        : "Add at least one project with a name and a result line."
    });

    var hasEdu = (resume.education || []).some(function (ed) {
      return /b\.?tech|bachelor|b\.s|b\.a|m\.s|master/i.test(ed.degree || "");
    });
    checks.push({
      ok: hasEdu,
      label: "Education heading",
      detail: hasEdu ? "Degree is listed in a standard Education section." : "Add a bachelor's or equivalent under Education."
    });

    var hasPython = /python/i.test(text);
    checks.push({
      ok: hasPython,
      label: "Python",
      detail: hasPython ? "Python is on the page." : "The JD asks for comfort with Python."
    });

    unicode.forEach(function (u) {
      checks.push({ ok: false, label: "Clean text", detail: u });
    });
    if (!unicode.length) {
      checks.push({ ok: true, label: "Clean text", detail: "No em dashes, curly quotes, or zero-width marks." });
    }

    phrases.forEach(function (p) {
      checks.push({ ok: false, label: "Human voice", detail: "Stock phrase: \"" + p + "\". Rewrite in plain English." });
    });
    if (!phrases.length) {
      checks.push({ ok: true, label: "Human voice", detail: "No common generator filler phrases." });
    }

    var layoutOk = true;
    checks.push({
      ok: layoutOk,
      label: "Single column",
      detail: "Export uses one column, standard headings, and no tables or icons."
    });
    checks.push({
      ok: true,
      label: "No watermark",
      detail: "Print and text exports do not add a logo, footer stamp, or hidden layer."
    });

    var failed = checks.filter(function (c) { return !c.ok; }).length;
    var checkScore = Math.round(((checks.length - failed) / checks.length) * 100);
    var overall = Math.round(keywordScore * 0.55 + checkScore * 0.45);

    return {
      overall: overall,
      keywordScore: keywordScore,
      checkScore: checkScore,
      keywords: keywords,
      checks: checks,
      unicode: unicode,
      phrases: phrases,
      text: text
    };
  }

  function sanitizeForExport(text) {
    return String(text || "")
      .replace(/[\u2013\u2014\u2015]/g, "-")
      .replace(/[\u2018\u2019]/g, "'")
      .replace(/[\u201C\u201D]/g, '"')
      .replace(/[\u00A0\u202F\u2007\u2009]/g, " ")
      .replace(/[\u200B\u200C\u200D\uFEFF\u2060\u00AD]/g, "")
      .replace(/[ \t]+\n/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim();
  }

  function looksLikeWatermark(html) {
    var lower = String(html || "").toLowerCase();
    return WATERMARK_MARKERS.some(function (m) { return lower.indexOf(m) !== -1; });
  }

  root.ATS = {
    collectText: collectText,
    scoreAts: scoreAts,
    sanitizeForExport: sanitizeForExport,
    looksLikeWatermark: looksLikeWatermark,
    findUnicodeIssues: findUnicodeIssues,
    findAiPhrases: findAiPhrases
  };
})(window);
